services:
  frontend:
    container_name: frontend-for-go-app
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./html/test.html:/usr/share/nginx/html/index.html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
  
  backend:
    container_name: go-api
    image: app-go:latest
    ports:
      - "8000:8000"
    restart: unless-stopped

